export type LegalSection = {
  heading: string;
  paragraphs: string[];
};

export type LegalDocument = {
  title: string;
  lastUpdated: string;
  sections: LegalSection[];
};

export const SUPPORT_EMAIL = 'info@deltaresume.com';

export const TERMS_OF_SERVICE: LegalDocument = {
  title: 'Terms of Service',
  lastUpdated: 'July 5, 2026',
  sections: [
    {
      heading: '1. Acceptance of Terms',
      paragraphs: [
        'By accessing or using Delta Resume (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.',
      ],
    },
    {
      heading: '2. Description of Service',
      paragraphs: [
        'Delta Resume is a tool that suggests edits to your resume based on a job description you provide. Suggestions are generated by an AI model and are provided for informational purposes only.',
        'We do not guarantee that using the Service will result in interviews, job offers, or any particular employment outcome. You are solely responsible for reviewing and approving any changes to your resume before using it.',
      ],
    },
    {
      heading: '3. Accounts and Credits',
      paragraphs: [
        'You may use the Service as a guest with a limited number of free credits, or create an account for additional credits and features. One credit is consumed per tailoring run.',
        'Paid subscriptions renew automatically until cancelled. You may cancel at any time, and cancellation takes effect at the end of the current billing period. Except where required by law, payments are non-refundable.',
      ],
    },
    {
      heading: '4. Acceptable Use',
      paragraphs: [
        'You agree not to misuse the Service, including by attempting to circumvent credit limits, submitting content you do not have the right to use, submitting unlawful or harmful content, or interfering with the operation of the Service.',
      ],
    },
    {
      heading: '5. Your Content',
      paragraphs: [
        'You retain all rights to the resume text and job descriptions you submit. You grant us a limited license to process and store this content solely to provide and improve the Service, including sending it to our AI provider to generate suggestions.',
      ],
    },
    {
      heading: '6. Disclaimer of Warranties',
      paragraphs: [
        'The Service is provided "as is" and "as available" without warranties of any kind, whether express or implied. AI-generated suggestions may contain errors or inaccuracies.',
      ],
    },
    {
      heading: '7. Limitation of Liability',
      paragraphs: [
        'To the maximum extent permitted by law, Delta Resume shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim.',
      ],
    },
    {
      heading: '8. Changes to These Terms',
      paragraphs: [
        'We may update these terms from time to time. Continued use of the Service after changes take effect constitutes acceptance of the revised terms.',
      ],
    },
    {
      heading: '9. Contact',
      paragraphs: [`Questions about these terms can be sent to ${SUPPORT_EMAIL}.`],
    },
  ],
};

export const PRIVACY_POLICY: LegalDocument = {
  title: 'Privacy Policy',
  lastUpdated: 'July 5, 2026',
  sections: [
    {
      heading: '1. Information We Collect',
      paragraphs: [
        'Resume text and job descriptions you submit for tailoring, which are processed to generate suggestions and are not stored on our servers.',
        'Resumes you explicitly save to your account for reuse.',
        'Account information such as your email address if you sign up, managed by our authentication provider, Clerk.',
        'For guest users, a browser fingerprint and IP address used solely to enforce free credit limits.',
        'Basic usage analytics to understand how the Service is used.',
        'Error and performance diagnostics via Sentry, which may include anonymized stack traces, request metadata, and privacy-masked session replays when an error occurs.',
      ],
    },
    {
      heading: '2. How We Use Your Information',
      paragraphs: [
        'We use your resume text and job descriptions to generate tailoring suggestions. This content is sent to Anthropic, our AI provider, to produce the suggestions.',
        'Tailoring content is processed in memory only and discarded after your results are returned. Saved resumes are stored so you can reuse them across sessions.',
        'We do not sell your personal information or use your resume content to train AI models.',
      ],
    },
    {
      heading: '3. Third-Party Services',
      paragraphs: [
        'Clerk handles authentication and billing, including payment processing. We never see or store your full payment details.',
        'Anthropic processes resume and job description text to generate suggestions, subject to their data usage policies.',
        'Sentry receives error and performance diagnostics to help us operate and improve the Service. Session replays are privacy-masked and captured only when an error occurs.',
      ],
    },
    {
      heading: '4. Data Retention and Deletion',
      paragraphs: [
        'Saved resumes are retained while your account is active. Resume text and job descriptions submitted for tailoring are not retained after processing. Contact us to request deletion of your data, and we will remove it within a reasonable period.',
      ],
    },
    {
      heading: '5. Security',
      paragraphs: [
        'We take reasonable measures to protect your data, but no method of transmission or storage is completely secure. Avoid including highly sensitive information (such as government ID numbers) in resume text you submit.',
      ],
    },
    {
      heading: '6. Changes to This Policy',
      paragraphs: [
        'We may update this policy from time to time. Material changes will be reflected by the "last updated" date above.',
      ],
    },
    {
      heading: '7. Contact',
      paragraphs: [`Privacy questions or data deletion requests can be sent to ${SUPPORT_EMAIL}.`],
    },
  ],
};
